#
# Copyright (C) 2024 - Martijn Benjamin
#
# -----
# Written for the Monumental technical assessment
# "Visualizing a Robotic Crane"
# -----
#
services:

  # The Robot hmi
  hmi:
    container_name: robot-hmi
    build:
      context: hmi
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./hmi:/usr/src/hmi
      - /usr/src/hmi/node_modules
    restart: always
    networks:
      - monumental-hmi
    depends_on:
      - api

  # The Robot API
  api:
    container_name: robot-api
    restart: always
    build:
      context: api
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    depends_on:
      - storage
    networks:
      - monumental-storage
      - monumental-hmi
    expose:
      - 3000:3000

  # MongoDB Storage
  storage:
    container_name: robot-state
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - monumental-storage
    expose:
      - 27017

networks:
  monumental-hmi:
  monumental-storage:
